### ISSUE TITLE
Client id and Client Secret Leaked publically

### ISSUE THREAD

**Issue by MilindPurswani** [yashrs/Digital-Ocean-Bot-Node#1]
Hey,

Your repository is leaking firebase client id and client secret publically along with a token. Can we take this off?

https://github.com/yashrs/Digital-Ocean-Bot-Node/blob/a62266ee795bc223dbd7493e4048a738dff6af16/firebase/functions/index.js#L56

**Comment by yashrs** [comment]
They don't work anymore @MilindPurswani
